django/led_matrix/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('log/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('store/', include('store.urls')),
]

django/main/urls.py
from django.urls import path
from . import views

app_name = "main"
urlpatterns = [
	path("", views.IndexView.as_view(), name='index'),
	path("save_config/<int:user_pk>", views.save_config, name="save_config"),
	path("config/<int:config_pk>", views.config_load, name="config")
]

django/store/urls.py
from django.urls import path
from . import views

app_name = "store"
urlpatterns = [
	path("", views.StoreView.as_view(), name='index'),
]

django/users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
	# path("/registration", views.RegView.as_view(), name='reg'),
	path("registration/", views.registration, name="reg"),
	path("login/", views.login_def, name="log"),
	path("logout/", views.logout_def, name="logout"),
	path("profile/<int:user_pk>", views.profile, name="profile"),
	path("change_password/<int:user_pk>", views.change_password, name="change_password"),
	path("change_email/<int:user_pk>", views.change_email, name="change_email"),
]

django/main/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Config(models.Model):
	name = models.CharField(max_length=200)
	date = models.DateTimeField("date created")
	configuration = models.TextField()
	author = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self) :
		return self.name

django/store/models.py
from django.db import models

# Create your models here.

django/main/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone

from django.contrib.auth.models import User
from .models import Config

class IndexView(generic.ListView):
	template_name = "main/index.html"

	def get_queryset(self) :
		pass

def save_config(request, user_pk) :
	user = get_object_or_404(User, pk=user_pk)

	Config.objects.create(name=request.POST["name"],
						  date=timezone.now(),
						  configuration=request.POST['configuration'],
						  author=user)

	return HttpResponseRedirect(reverse('main:index'))

def config_load(request, config_pk) :
	config = get_object_or_404(Config, pk = config_pk)
	user = User.objects.get(pk = config.author_id)

	return render(request,
				  "main/config_load.html",
				  {
				  	"config": config,
				  	"user": user
				  })

django/store/views.py
from django.shortcuts import render
from django.views import generic

from main.models import Config

# Create your views here.
class StoreView(generic.ListView) :
	model = Config
	template_name = 'store/index.html'
	context_object_name = 'configs'

	def get_queryset(self) :
		return Config.objects.all()

django/users/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views import generic
from django.db.utils import IntegrityError

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from main.models import Config

def registration(request) :  # registation
	if request.POST :
		try:
			user = User.objects.create_user(username = request.POST['username'],
											password = request.POST['password'])
			user.save()
			return HttpResponseRedirect(reverse("users:log"))	
		except IntegrityError:
			return render(request,
					      "registration/reg.html",
					      {
					      	"error_message": "Username is taken"
					      })
		
	else :
		return render(request, "registration/reg.html")

def login_def(request) :  # login
	if request.POST :
		user = authenticate(request,
							username = request.POST['username'],
							password = request.POST['password'])
		if user is not None :
			login(request, user)
			return HttpResponseRedirect(reverse("main:index"))
		else :
			return render(request,
					      "registration/login.html",
					      {
					      	"error_message": "Invalid left login or password"
					      })
	else :
		return render(request, "registration/login.html")

def logout_def(request) :  # logout
	logout(request)
	return HttpResponseRedirect(reverse("main:index"))

def profile(request, user_pk) :  # Profile
	user = get_object_or_404(User, pk = user_pk)
	configs = Config.objects.filter(author = user_pk)

	return render(request,
				  "registration/profile.html",
				  {
				  	"user": user if user else False,
				  	"configs": configs
				  })

def change_password(request, user_pk) :
	user = User.objects.get(pk = user_pk)

	if request.user.id == user.id :
		user.set_password(request.POST["password"])
		user.save()
		return HttpResponseRedirect(reverse("users:log"))
	else :
		return HttpResponse("fuck you") # change text error

def change_email(request, user_pk) :
	user = User.objects.get(pk = user_pk)

	if request.user.id == user.id:
		user.email = request.POST["email"]
		user.save()
		return HttpResponseRedirect(reverse("users:profile", args = (user_pk,)))
	else :
		return HttpResponse("fuck you") # change text error

django/templates/main/config_load.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<link rel="stylesheet" type="text/css" href="{% static 'main/index.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'main/input_range.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'main/header.css' %}">
</head>
<body>

	<div id="drop-zone"></div>

	<header>
		<div class="header_elem">
			<a href="{% url 'store:index' %}">Store</a>
		</div>
		<div class="header_elem">
			<a href="{% url 'main:index' %}">Led Matrix</a>
		</div>
		<div class="header_elem">
			{% if request.user.is_authenticated %}
				<div class="log_reg">
					<a href="{% url 'users:profile' request.user.id %}">Profile</a>
				</div>
				<div class="log_reg">
					<a href="{% url 'users:logout' %}">Out</a>
				</div>
			{% else %}
				<div class="log_reg">
					<a href="{% url 'users:log' %}">Log</a>
				</div>
				<div class="log_reg">
					<a href="{% url 'users:reg' %}">Reg</a>
				</div>
			{% endif %}
		</div>
	</header>

	<div class="window" id="window">
		<div class="draw" id="draw"></div>
		<div class="side_panel left_panel" id="left_panel">
			<button class="left_panel_button left_top_button" id="clear" onclick="clear_win();">Clear</button>
			<button class="left_panel_button left_bottom_button" id="switch_color">
				<input type="number" placeholder="X count" id="h_count" class="settings_left_panel">
				<input type="number" placeholder="Y count" id="v_count" class="settings_left_panel">
			</button>
		</div>
		
		{% if request.user.is_authenticated %}
			<div class="side_panel right_panel">
				<button class="right_panel_button right_top_button" onclick="export_file();">File</button>
				<button class="right_panel_button right_bottom_button">
					<form style="height: 100%; width: 100%;" class="form" method="post" action="{% url 'main:save_config' request.user.id %}">
						{% csrf_token %}
						<input type="text" name="configuration" id="configuration">
						<input type="text" name="name" placeholder="Name config" class="settings_right_panel">
						<input type="submit" value="Save config" class="settings_right_panel">
					</form>
				</button>
			</div>
		{% else %}
			<button class="side_panel right_panel" onclick="export_file();" style="border: solid 1px white;">File</button>
		{% endif %}
		
	</div>

	<input type="text" style="display: none;" id="load_config" value="{{ config.configuration }}">

</body>

	<script type="text/javascript" src="{% static 'main/load_config.js' %}"></script>

</html>

django/templates/main/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<link rel="stylesheet" type="text/css" href="{% static 'main/index.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'main/input_range.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'main/header.css' %}">
</head>
<body>

	<div id="drop-zone"></div>

	<header>
		<div class="header_elem">
			<a href="{% url 'store:index' %}">Store</a>
		</div>
		<div class="header_elem">
			<a href="{% url 'main:index' %}">Led Matrix</a>
		</div>
		<div class="header_elem">
			{% if request.user.is_authenticated %}
				<div class="log_reg">
					<a href="{% url 'users:profile' request.user.id %}">Profile</a>
				</div>
				<div class="log_reg">
					<a href="{% url 'users:logout' %}">Out</a>
				</div>
			{% else %}
				<div class="log_reg">
					<a href="{% url 'users:log' %}">Log</a>
				</div>
				<div class="log_reg">
					<a href="{% url 'users:reg' %}">Reg</a>
				</div>
			{% endif %}
		</div>
	</header>

	<div class="window" id="window">
		<div class="draw" id="draw"></div>
		<div class="side_panel left_panel" id="left_panel">
			<button class="left_panel_button left_top_button" id="clear" onclick="clear_win();">Clear</button>
			<button class="left_panel_button left_bottom_button" id="switch_color">
				<input type="number" placeholder="X count" id="h_count" class="settings_left_panel">
				<input type="number" placeholder="Y count" id="v_count" class="settings_left_panel">
			</button>
		</div>
		
		{% if request.user.is_authenticated %}
			<div class="side_panel right_panel">
				<button class="right_panel_button right_top_button" onclick="export_file();">File</button>
				<button class="right_panel_button right_bottom_button">
					<form style="height: 100%; width: 100%;" class="form" method="post" action="{% url 'main:save_config' request.user.id %}">
						{% csrf_token %}
						<input type="text" name="configuration" id="configuration">
						<input type="text" name="name" placeholder="Name config" class="settings_right_panel">
						<input type="submit" value="Save config" class="settings_right_panel">
					</form>
				</button>
			</div>
		{% else %}
			<button class="side_panel right_panel" onclick="export_file();" style="border: solid 1px white;">File</button>
		{% endif %}
		
	</div>

</body>
	
	<script type="text/javascript" src="{% static 'main/index.js' %}"></script>

</html>

django/templates/store/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Store</title>

	<link rel="stylesheet" type="text/css" href="{% static 'store/index.css' %}">

	<style>
		html, body {
			background-color: black;
		}
	</style>

</head>
<body>

	<div id="background"></div>

	<div id="form">
		<div class="form_elem home">
			<a href="{% url 'main:index' %}">----> Home <----</a>
		</div>
		<div class="form_elem search">
			<input class="search_elem" type="text" name="" placeholder="search here">
			<input class="search_elem" type="submit" value="search">
		</div>
		<div class="form_elem configutarions">
			<hr>
			{% if configs %}
				{% for config in configs %}
					<div class="config">
						<div class="config_top">
							<div class="config_info config_elem_top">{{ config.id }}</div>
							<div class="config_info config_elem_top"><a href="{% url 'main:config' config.id %}">{{ config.name }}</a></div>
							<div class="config_info config_elem_top"><a href="{% url 'users:profile' config.author.id %}">{{ config.author }}</a></div>
						</div>	
						<div class="config_info config_bottom">{{ config.date }}</div>
					</div>
				{% endfor %}
			{% else %}
				<div class="config" style="line-height: 300%; text-align: center;">
					No saved configurations yet, be the first
				</div>
			{% endif %}
		</div>
	</div>

</body>
</html>